### ISSUE TITLE
Select for Update/Delete

### ISSUE THREAD

**Issue by gkorland** [freestrings/jsonpath#1]
Is there a way to select for update/delete?

```rust
let result = selector
    .path("$..[?(@.age >= 30)]").unwrap()
    .value(&json_obj).delete() 
```

**Comment by freestrings** [comment]
Hi,

APIs for handling for "mut json_obj" are not yet supported. I am developing query and transform functions for "&json_obj" first. For example,
```rust
selector
     .select_then()?
     .map(|mut v | { .. })
     .map_as(|v: result::Result<Person, String>| { .. })?
     .take_as::<Person>()?;
```

**Comment by gkorland** [comment]
Any progress on that? Do you need any help here?

**Comment by freestrings** [comment]
Hi, sorry for the late response. I didn’t notice your comment. the "map" and the "map_as" function merged in master.

**Comment by gkorland** [comment]
Thanks! Are you planing to add a way to mutate the JSON based on jsonpath?

**Comment by freestrings** [comment]
yes, i have a plan to write the APIs to mutate the JSON. 
It will look roughly like this:

```
selector.path().value().map(..)
  .fork()    
    .map(..)
    .merge()
```

or

```
selector.path(..).value().map(..)
    .into_mut()
        .delete(path)
        .replace(path, obj)
        .insert(path, obj)
        .commit()
```

do you have better idea?

**Comment by gkorland** [comment]
what will .into_mut() do?

**Comment by freestrings** [comment]
I keep thinking about "into_mut" but the basic meaning of "into_mut" is to clone the current context.

```
let json = json!({
    b: {
        c: 1
    }
})
```

> without "into_mut"

```
selector
    .value(&json)
    .path("$.a.b.c")
    .delete()
    .get()

==>
{
    b: {}
}
```

> with "into_mut"

```
selector
    .value(&json)
    .path("$.a.b.c")
    .into_mut() // create Mutable { .. }
    .delete()
    .get() // Mutable's get()

>>
{
    b: {}
}


selector
    .value(&json)
    .path("$.a.c.d")
    .into_mut()
    .delete()
    .end() // destroy Mutable
    .get() // original value

>>
{
    b: {
        c: 1
    }
}


selector
    .value(&json)
    .path("$.a.c.d")
    .into_mut()
    .delete()
    .commit() //
    .get()

>>
{
    b: {}
}

**Comment by gkorland** [comment]
Looks good! 
My original thought was to create another struct called Decorator that will be a variant of Selector and will get mutable reference of the doc, this way you won't have to clone it.

**Comment by freestrings** [comment]
Thanks for comment.
i think that the "without into_mut" example is solution for your question. like your first comment. i will add "Modifiable(?) trait" first.

**Comment by gkorland** [comment]
OK, I'll be glad to test it once you have it ready, my deepest concern is about performance.
Same with Selector select if it could have been a slice of the original JSON and not a copy that could have been much more efficient

**Comment by gkorland** [comment]
Great!!
