### ISSUE TITLE
Negative slice out of bounds does not return values

### ISSUE THREAD

**Issue by cburgmer** [freestrings/jsonpath#35]
It took me more than 6 months to finally find another issue. And I for sure have tried a lot :)

Selector: `$[-4:]`

Input:
  ```
  ["first", "second", "third"]
  ```

Expected output:
  ```
  ["first", "second", "third"]
  ```
  Actual output:
  ```
  []
  ```

Compare https://cburgmer.github.io/json-path-comparison/. For reference, the output was generated by the program in https://github.com/cburgmer/json-path-comparison/tree/master/implementations/Rust_jsonpath_lib.

**Comment by freestrings** [comment]
@cburgmer Very Thanks!!
