### ISSUE TITLE
select returns value from array in json object instead of nothing

### ISSUE THREAD

**Issue by yoav-steinberg** [freestrings/jsonpath#50]
Consider:
```rust
    let j = json!({"f": [1,2,3]});
    let mut sel = Selector::new();
    let r = sel.str_path("$[0]").unwrap().value(&j).select().unwrap();
    for v in r {
        println!("{}", v);
    }
```
I'd expect nothing to be returned since the array is under the `"f"` field in the object and we're trying to reference the top level as if it's an array. Surprisingly the code prints `1` as if the array is in the top level.
This seems like a bug.

**Comment by freestrings** [comment]
It looks like a bug as you comment. I will check the results of other JSONPATH libraries.
Thanks. :)
