### ISSUE TITLE
More flexible API

### ISSUE THREAD

**Issue by michaelvoronov** [freestrings/jsonpath#60]
Hi, thank you for the library!

I am trying to use select with `Vec<Rc<serde_json::Value>>`, but it seems that the only option I have now is to construct a new array-like `serde_json::Value`. What about adding (or even replacing existing `select` methods) new pub trait for navigating in json or some other more flexible API? F.e. wolker that can in-depth and in-width move across json could suit here.

**Comment by freestrings** [comment]
Hi. The answer was very late.

It is understood as saying that it would be nice to have a `walker` for exploration. The purpose is to find a specific JSON value with "path expression" but I don't know why walker is needed.

If you explain the use case with pseudo code, it will be a little more understandable.

Thank you.
