### ISSUE TITLE
New release on crates.io?

### ISSUE THREAD

**Issue by olix0r** [freestrings/jsonpath#68]
Hello,

I'm working on a project that pulls in `jsonpath_lib` as a transitive dependency, and jsonpath's unexpected dependency on `env_logger` causes [`cargo-deny`](https://embarkstudios.github.io/cargo-deny/) conflicts:

```
error[B004]: found 2 duplicate entries for crate 'env_logger'
   │  
30 │ ╭ env_logger 0.7.1 registry+https://github.com/rust-lang/crates.io-index
31 │ │ env_logger 0.8.3 registry+https://github.com/rust-lang/crates.io-index
   │ ╰──────────────────────────────────────────────────────────────────────^ lock entries
   │  
```

I see that this dependency has been removed in https://github.com/freestrings/jsonpath/pull/66.

Are you planning to do a release sometime soon? I'd love to be able to be able to avoid the unnecessary dependency in my release code. Please let me know if there's anything I can do to make this easier :) Thanks!

**Comment by freestrings** [comment]
Thanks. I will new release soon. :)

**Comment by olix0r** [comment]
Thank you @freestrings!
