### ISSUE TITLE
Improve Parser and Tokenizer performance

### ISSUE THREAD

**Issue by gkorland** [freestrings/jsonpath#72]
When profiling the compile function you can see that a lot of time is wasted on memory allocations.
It seems like most of them can be avoided it the the Parser and the Tokenizer will try to work with slices from the original path and not allocate new Strings

![image](https://user-images.githubusercontent.com/753206/125584225-37bab30e-3499-4480-a08e-4fcb8d4e206a.png)

ref https://github.com/RedisJSON/RedisJSON/issues/424 & https://github.com/RedisJSON/RedisJSON/issues/425

**Comment by freestrings** [comment]
The "paths" and "selector" modules have been rewritten. there is also a performance improvement with the part you raised the issue. can you test it with the newly written module?

**old**
https://github.com/freestrings/jsonpath/blob/feature/refactoring/benchmark/flame.old.svg

**new**
https://github.com/freestrings/jsonpath/blob/feature/refactoring/benchmark/flame.svg

You can check it in the feature/refactoring branch.
https://github.com/freestrings/jsonpath/tree/feature/refactoring

see: select function
https://github.com/freestrings/jsonpath/blob/feature/refactoring/src/lib.rs#L342

**Comment by freestrings** [comment]
Since there is no response, I will close the issue as it has been resolved.
